# This file was generated by GoReleaser. DO NOT EDIT.
class Chronic < Formula
  desc "A tool that hides output unless the command fails; now in Go!"
  homepage "https://github.com/docwhat/chronic"
  version "1.0.10"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/docwhat/chronic/releases/download/v1.0.10/chronic_1.0.10_darwin_amd64.tar.gz"
    sha256 "d9be7bd8ed94b1fcdc8a58c47382f032c206d5e28603bf3573f3f9cb72fec9e0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/docwhat/chronic/releases/download/v1.0.10/chronic_1.0.10_linux_amd64.tar.gz"
      sha256 "f621804fbfd92932a6e3bc63d855b90f92ba6851fa6b0db79712ab5ce190991d"
    end
  end

  def install
    bin.install "chronic"
  end

  test do
    system "#{bin}/chronic"
  end
end
