# This file was generated by GoReleaser. DO NOT EDIT.
class Chronic < Formula
  desc "A tool that hides output unless the command fails; now in Go!"
  homepage "https://github.com/docwhat/chronic"
  version "1.0.11"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/docwhat/chronic/releases/download/v1.0.11/chronic_1.0.11_darwin_amd64.tar.gz"
    sha256 "29247acc6148f258569f0d8272816f67cac20cf0a9f88dce6ca4152701a4b8fd"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/docwhat/chronic/releases/download/v1.0.11/chronic_1.0.11_linux_amd64.tar.gz"
      sha256 "8a44e85e144d3fb0d310a0e18c644758f01406ea853af8f6374ecbb2ec6d4c29"
    end
  end

  def install
    bin.install "chronic"
  end

  test do
    system "#{bin}/chronic"
  end
end
