# This file was generated by GoReleaser. DO NOT EDIT.
class Chronic < Formula
  desc "A tool that hides output unless the command fails; now in Go!"
  homepage "https://github.com/docwhat/chronic"
  version "1.0.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/docwhat/chronic/releases/download/v1.0.9/chronic_1.0.9_darwin_amd64.tar.gz"
    sha256 "c90d9f3ba04111bcadd4533fe086a0c3995a85c6d820d283c24aa84c057bfdc7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/docwhat/chronic/releases/download/v1.0.9/chronic_1.0.9_linux_amd64.tar.gz"
      sha256 "271bbf568db70b65133010d4ee3d5507c7c4e67b944edc9f4cb1aa314f672c2c"
    end
  end

  def install
    bin.install "chronic"
    bin.install "chronic"
  end

  test do
    system "#{bin}/chronic"
  end
end
