# This file was generated by GoReleaser. DO NOT EDIT.
class Chronic < Formula
  desc "A tool that hides output unless the command fails; now in Go!"
  homepage "https://github.com/docwhat/chronic"
  version "1.0.11"

  if OS.mac?
    url "https://github.com/docwhat/chronic/releases/download/v1.0.11/chronic_1.0.11_darwin_amd64.tar.gz"
    sha256 "c5713a49a6f588d8a5c3b130e611f4536e867274b1413283aa83d189b7739d67"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/docwhat/chronic/releases/download/v1.0.11/chronic_1.0.11_linux_amd64.tar.gz"
      sha256 "0ec803ce1672501e12fa90ae77a56805f5e7deac898679e1dca1a084a98b1da2"
    end
  end

  def install
    bin.install "chronic"
  end

  test do
    system "#{bin}/chronic"
  end
end
