# This file was generated by GoReleaser. DO NOT EDIT.
class Chronic < Formula
  desc "A tool that hides output unless the command fails; now in Go!"
  homepage "https://github.com/docwhat/chronic"
  version "1.0.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/docwhat/chronic/releases/download/v1.0.8/chronic_1.0.8_darwin_amd64.tar.gz"
    sha256 "d5c2873b18c9fbd70574188366aaec68522f388a291d5482b19ad6c3ce23d214"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/docwhat/chronic/releases/download/v1.0.8/chronic_1.0.8_linux_amd64.tar.gz"
      sha256 "264f391301193d7319817630963eac4623d020e7c3db8a9557f54b68c1c8c3f7"
    end
  end

  def install
    bin.install "chronic"
    bin.install "chronic"
  end

  test do
    system "#{bin}/chronic"
  end
end
